spring.datasource.url=jdbc:postgresql://localhost:5432/skymetrics_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=BestHackathon2026SuperSecretKeyWithVeryLongStringSoItIsSecureEnoughJavaEditionSuperSecure))
jwt.expirationMs=86400000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=8080