version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: skymetrics_db
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: skymetrics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skymetrics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: skymetrics_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/skymetrics_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  backend-python:
    build:
      context: ../../python
      dockerfile: Dockerfile
    container_name: skymetrics_backend_python
    ports:
      - "8000:8000"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: skymetrics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
